name: jurnal_cuan
description: Jurnal Trading App with Firebase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # UI & Utils
  image_picker: ^1.0.7
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  lottie: ^3.1.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
